name: 'dbt-snowflake'
description: 'Runs DBT on Snowflake.'
inputs:
  command:  # id of input
    description: 'DBT commands to execute'
    required: true
    default: 'dbt build'
outputs:
  logs: # id of output
    description: 'Logs from DBT job execution.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
